(rule
 (targets
  BinNat.ml BinNat.mli
  BinNums.ml BinNums.mli
  BinPos.ml BinPos.mli
  Datatypes.ml Datatypes.mli
  HashTable.ml HashTable.mli
  HashTableBits.ml HashTableBits.mli
  HashTableBucket.ml HashTableBucket.mli
  List.ml List.mli
  Nat.ml Nat.mli
  PosDef.ml PosDef.mli)
 (deps
  ../HashTableReferenceExtract.v ../HashTableSpec.vo ../HashTableBits.vo
  ../HashTableBucket.vo ../HashTable.vo)
 (action
  (chdir %{workspace_root}
   (run %{bin:rocq} compile -q -Q . "" HashTableReferenceExtract.v))))

(library
 (name hashtable_reference_extracted)
 (wrapped false)
 (flags (:standard -w -a))
 (modules :standard))
